//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamDBCopyCatMVC.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SteamDBCopyCatEntities : DbContext
    {
        public SteamDBCopyCatEntities()
            : base("name=SteamDBCopyCatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TabelBarang> TabelBarangs { get; set; }
    
        public virtual ObjectResult<NewestItemTop5_Result> NewestItemTop5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NewestItemTop5_Result>("NewestItemTop5");
        }
    
        public virtual ObjectResult<ShowListBarang_Result> ShowListBarang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowListBarang_Result>("ShowListBarang");
        }
    }
}
