//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamDBCopyCatMVC.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SteamDBCopyCatEntities : DbContext
    {
        public SteamDBCopyCatEntities()
            : base("name=SteamDBCopyCatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TabelBarang> TabelBarangs { get; set; }
        public virtual DbSet<Akun> Akuns { get; set; }
        public virtual DbSet<TabelDaftarBarang> TabelDaftarBarangs { get; set; }
        public virtual DbSet<TabelHarga> TabelHargas { get; set; }
        public virtual DbSet<TabelToko> TabelTokoes { get; set; }
    
        public virtual ObjectResult<NewestItemTop5_Result> NewestItemTop5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NewestItemTop5_Result>("NewestItemTop5");
        }
    
        public virtual ObjectResult<ShowListBarang_Result> ShowListBarang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowListBarang_Result>("ShowListBarang");
        }
    
        public virtual ObjectResult<Nullable<int>> Create_Account(string password, string email)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Create_Account", passwordParameter, emailParameter);
        }
    
        public virtual ObjectResult<string> GetLoginInfo(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetLoginInfo", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<ListHargaBerbagaiToko_Result> ListHargaBerbagaiToko()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListHargaBerbagaiToko_Result>("ListHargaBerbagaiToko");
        }
    }
}
