//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamDBCopyCatMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelHarga
    {
        public int ID_ListHarga { get; set; }
        public Nullable<int> ID_Toko { get; set; }
        public Nullable<int> ID_NamaBarang { get; set; }
        public Nullable<int> Harga { get; set; }
        public string NamaBarangs { get; set; }
    
        public virtual TabelDaftarBarang TabelDaftarBarang { get; set; }
        public virtual TabelToko TabelToko { get; set; }
    }
}
