//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamDBCopyCatMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelDaftarBarang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabelDaftarBarang()
        {
            this.TabelHargas = new HashSet<TabelHarga>();
        }
    
        public int ID_Barang { get; set; }
        public string Nama_Barang { get; set; }
        public string Tipe_Barang { get; set; }
        public Nullable<bool> Halal { get; set; }
        public byte[] Images { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabelHarga> TabelHargas { get; set; }
    }
}
